# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web-dev-win" do |c|
    c.vm.box = "ubuntu/xenial64"
    c.vm.provision :shell, path: "provision/web-dev-win.sh"
    c.vm.network "private_network", ip: "192.168.35.10"
    c.vm.network "forwarded_port", guest: 4200, host: 4200, host_ip: "127.0.0.1"
    c.vm.provider "virtualbox" do |vb|
        vb.name = "web-dev-win"
        vb.memory = "512"
    end
  end
end